### ISSUE TITLE
Error: java.lang.NoClassDefFoundError:net/minecraftforge/fml/client/gui/GuiUtils

### ISSUE THREAD

**Issue by Heliosarc** [killjoy1221/TabbyChat-2#114]
Log: https://pastebin.com/Q09T04UM

How to recreate crash;

1) Downloaded latest Tabbychat 2 build: https://travis-ci.org/github/killjoy1221/TabbyChat-2/builds/651285736
2) Downloaded latest Kottle build: https://www.curseforge.com/minecraft/mc-mods/kottle/files/2895068
3) Both mods and only those two mods were inside .minecraft/mods
4) Made sure to have Forge 1.15.1-30.0.50 (I tried 1.15.2, but forge came back with Tabbychat only working on 1.15.1)
5) Launched the game normally, everything seems to work fine. 
6) Create new super-flat world and enter once finished.
7) Try to do "/" (Game Crash)

I tried again a couple times to recreate the crash to see if it was consistent or just a one-time thing. Needless to say, it is consistent. Whenever I try to move around, it won't let me, but doesn't crash. It's when I open chat that the crash happens.

After Minecraft crashes, an error box pops up with "Error: java.lang.NoClassDefFoundError:net/minecraftforge/fml/client/gui/GuiUtils"

Anyway to resolve this?
